name: Production Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: 26.x
          elixir-version: 1.16.x
      - run: mix deps.get
      - run: mix test

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home${{ secrets.USERNAME }}/file_server
            git pull
            docker compose down
            docker compose up --build -d
