name: Production Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "26"
          elixir-version: "1.16.2"

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test

      - name: Build release
        run: MIX_ENV=prod mix release

      - name: Compress build
        run: tar -czf release.tar.gz -C _build/prod/rel file_server

      - name: Upload release to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: release.tar.gz
          target: /home/${{ secrets.USERNAME }}/file_server/release.tar.gz

      - name: Deploy release
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/${{ secrets.USERNAME }}/file_server
            tar -xzf release.tar.gz
            rm -rf old_release
            mv current_release old_release || true
            mv file_server current_release
            current_release/bin/file_server stop || true
            current_release/bin/file_server daemon
